version: '3'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    restart: always
    ports:
      - '3306:3306'
    environment:
      -  MYSQL_DATABASE=my-app-db
      -  MYSQL_HOST=localhost
      -  MYSQL_PORT=3306
      -  MYSQL_USER=root
      -  MYSQL_PASSWORD=password
      -  MYSQL_ROOT_PASSWORD=password

  app:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/src
    ports:
      - '8000:8000'
    depends_on:
      - db