# Generated by Django 3.0 on 2020-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emessage',
            name='chunk_id',
            field=models.IntegerField(default=1, verbose_name='Chunk number'),
        ),
    ]
